/*
 * Project: 	Data Generation and Printer Module
 * Description: This program simulates a data generation and printing process.
 *              Random bytes are generated and stored in a dynamic buffer.
 *              Every 10 seconds, if the buffer contains at least 50 bytes,
 *              the latest 50 bytes are printed and then removed from the buffer.
 *				If Not generated then skip the printing and removing of the data
 *
 * Author: Vinay Kumar K Deshpande
 * Date: 06/02/2025
 *
 * 
 * 
 */


#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>
#define MAX_BYTES 50  
unsigned char *buffer = NULL;  
int buffer_size = 0;

 

void data_generator(int data_module_elapsed_time) {
	/* Generate Data 0 and 5 bytes */
    int num_bytes = rand() % 6;  
    if (num_bytes > 0) {
        /* Reallocating buffer for new data */
        buffer = realloc(buffer, buffer_size + num_bytes);
        if (!buffer) {
            //printf("ERROR Memory allocation failed!\n");
            exit(1);
        }
        for (int i = 0; i < num_bytes; i++) {
            unsigned char rand_byte = rand() % 256;  // Generate random byte
            buffer[buffer_size++] = rand_byte;  // Append new byte
            //printf("**** DEBUGGING: Time: %d s - Generated byte: %02X ****\n", data_module_elapsed_time, rand_byte);
        }
    }
    //printf("**** DEBUGGING Time: %d s - Added %d bytes. Current buffer size: %d ****\n", data_module_elapsed_time, num_bytes, buffer_size);
}

 

void data_printer(int data_module_elapsed_time) {
    //printf("**** DEBUGGING:  Time: %d s - Checking buffer. Current buffer size: %d ****\n", data_module_elapsed_time, buffer_size);
    if (buffer_size >= MAX_BYTES) {
        //printf(" ***** Time: %d s - Printing latest 50 bytes:\n", data_module_elapsed_time);
        /* Print lastest 50 bytes */
        for (int i = buffer_size - MAX_BYTES; i < buffer_size; i++) {
            //printf("%02X ", buffer[i]);
        }
        //printf("\n");
        /* Debug message: Print buffer before Deleting */
        //printf("**** DEBUGGING :  Before Deletion -> Buffer size = %d, Memory_Address = %p ****\n", buffer_size, (void *)buffer);
        /* Remove the latest 50 bytes to reduce the unwanted buffer size */
        buffer_size -= MAX_BYTES;
        
        /* Reallocate memory */
        buffer = realloc(buffer, buffer_size);
        if (!buffer && buffer_size > 0) {
            printf("[ERROR] Memory reallocation failed!\n");
            exit(1);
        }

        /* Debug message: Print buffer after reallocation */
		//printf("**** DEBUGGING : After Reallocation -> Buffer_size: %d, Memory_Address: %p ****\n", buffer_size, (void *)buffer);
    } else {
        //printf("**** DEBUGGING : Time: %d s - Less than 50 bytes in buffer, skip print. ****\n", data_module_elapsed_time);
    }
}

 
/* Start Of the main */
int main() {
    srand(time(NULL));
    //printf("**** DEBUGGING : Start Generating the Random data ****\n ");
    int data_module_elapsed_time = 0;
    const int print_interval = 10;
    while (1) {
        data_generator(data_module_elapsed_time);
        sleep(1);
        data_module_elapsed_time++;
        if (data_module_elapsed_time % print_interval == 0) {
            data_printer(data_module_elapsed_time);
        }
    }
    /*Free allocated memory*/ 
    free(buffer);

    return 0;
}

